{% set name = "bpx" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bpx-{{ version }}.tar.gz
  sha256: 141f9056cf614d67515a05fd552d4fbc9af9d2c13c2555bc7efb1dfd25d7f1af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.6
    - pyparsing
    - pyyaml

test:
  imports:
    - bpx
    - bpx.interpolated_table
    - bpx.expression_parser
    - bpx.function
    - bpx.validators
    - bpx.schema
    - bpx.parsers
    - bpx.utilities
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: BPX schema and parsers
  dev_url: https://github.com/FaradayInstitution/BPX
  home: https://github.com/FaradayInstitution/BPX
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Saransh-cpp
